#theme: jekyll-theme-slate
theme: jekyll-theme-cayman
title: [Hollywood: a reflection of a patriarchal society ?]
description: [Examining the role of Womem in Hollywod and how it reflects our society ?]
